DROP SCHEMA IF EXISTS shareit cascade;

CREATE SCHEMA IF NOT EXISTS  shareit;




CREATE TABLE IF NOT EXISTS shareit.users (
       id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
       name varchar(50),
       email varchar(50),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS shareit.items (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50),
    description varchar(50),
    available boolean,
    user_id BIGINT,
    CONSTRAINT pk_items PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES shareit.users (id)
    );

CREATE TABLE IF NOT EXISTS shareit.bookings
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id BIGINT REFERENCES shareit.items(id),
    booker_id BIGINT REFERENCES shareit.users(id),
    status varchar(50),
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS shareit.comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_text varchar NOT NULL,
    item_id BIGINT REFERENCES shareit.items(id),
    author_id BIGINT REFERENCES shareit.users(id),
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT comments_pk PRIMARY KEY (id)
    );